---
title: "R Notebook"
output: html_notebook
---

# Avg number of beds each season

```{r}
library(tidyverse)
library(lubridate)
library(ggplot2)

beds <- read_csv(here::here("raw_data/beds_by_nhs_board_of_treatment_and_specialty.csv")) %>% 
        janitor::clean_names()

head(beds)

# interested in percentage of available beds
# data is structured to show avg daily percentage of available beds per hospital (id = "hb")
# comparing against the time of year "quarter"
```
## Cleaning

```{r}
# checking column is clean
beds %>% 
  count(quarter)

beds_season <- beds %>% 
  mutate(
    season = str_extract(quarter, "\\d{1}$"),
    season = recode(season, 
      "1" = "Winter",
      "2" = "Spring",
      "3" = "Summer",
      "4" = "Autumn"
    ),
    year = as.numeric(str_extract(quarter, "^\\d{4}"))
  )
```
## Making Graph

```{r}
beds_season %>% 
  group_by(season) %>% 
  summarise(avg_daily_beds_perc = mean(percentage_occupancy, na.rm = TRUE)) %>% 
  ggplot() +
  aes(x = season, y = avg_daily_beds_perc, label = str_c(round(avg_daily_beds_perc), "%")) +
  geom_text(nudge_y = 1, alpha = 0.8) +
  geom_col(fill = "turquoise", alpha = 0.8) +
  coord_cartesian(ylim = c(60, 80)) +
  theme_minimal()

beds_season %>% 
  group_by(season, year) %>% 
  summarise(avg_daily_beds_perc = mean(percentage_occupancy, na.rm = TRUE)) %>% 
  ggplot() +
  aes(x = season, y = avg_daily_beds_perc, label = str_c(round(avg_daily_beds_perc), "%")) +
  geom_text(nudge_y = 1.2, alpha = 0.8) +
  geom_col(fill = "turquoise", alpha = 0.8) +
  coord_cartesian(ylim = c(60, 80)) +
  facet_wrap(~year) +
  theme_minimal()
```

# Avg number of admissions each season (can be split by simd rating)

```{r}
admissions <- read_csv(here::here("raw_data/hospital_admissions_hb_simd_20220302.csv")) %>% 
        janitor::clean_names()

head(admissions)
```

## Cleaning

```{r}
admissions_date <- admissions %>% 
  mutate(
    year = str_extract(week_ending, "^\\d{4}"),
    monthday = str_extract(week_ending, "\\d{4}$"),
    month = str_extract(monthday, "^\\d{2}"),
    day = str_extract(monthday, "\\d{2}$"),
    date = ymd(str_c(year, month, day)),
    .before = 1
  ) %>% 
  select(-monthday)

head(admissions_date)
```

```{r}
library(tsibble)

duplicates(admissions_date)

# MAKING DATETIME TSIBBLE

admissions_dt <- admissions_date %>% 
  group_by(date) %>% 
  summarise(avg_admissions_by_week = mean(number_admissions)) %>% 
  as_tsibble()

class(admissions_dt$date)

admissions_plotly <- admissions_dt %>%
  ggplot() +
  aes(x = date, y = avg_admissions_by_week) +
  geom_line(color = "steelblue") +
  scale_x_date(name = "", limits = c(as.Date("2020-01-01", "%Y-%m-%d"), as.Date("2022-02-20", "%Y-%m-%d")), date_breaks = "3 months", 
               date_minor_breaks = "1 month") +
  labs(y = "Average Admissions(weekly)") +
  theme_minimal()

ggplotly(admissions_plotly)

## ADDING WINTER SHADING

winter_shading <- c(annotate(geom = "rect",
                             xmin = as_date("2020-01-01"),
                             xmax = as_date("2020-04-01"),
                             ymin = -Inf,
                             ymax = Inf,
                             alpha = 0.3,
                             fill = "turquoise"),
                    annotate(geom = "rect",
                             xmin = as_date("2021-01-01"),
                             xmax = as_date("2021-04-01"),
                             ymin = -Inf,
                             ymax = Inf,
                             alpha = 0.3,
                             fill = "turquoise"))

admissions_dt %>%
  ggplot() +
  geom_line(aes(x = date, y = avg_admissions_by_week), color = "steelblue") +
  winter_shading[1] +
  winter_shading[2] +
  scale_x_date(name = "", limits = c(as.Date("2020-01-01", "%Y-%m-%d"), as.Date("2022-02-20", "%Y-%m-%d")), date_breaks = "3 months", 
               date_minor_breaks = "1 month", date_labels = "%b %y") +
  labs(y = "Average Admissions(weekly)") +
  theme_minimal()

```

```{r}
library(infer)

# Null hypo is that the difference between Jan mean and other mean is 0
# Alternative is that the difference is > 0

admissions_test_data <- admissions_date %>% 
  select(month, number_admissions) %>% 
  mutate(january = case_when(month == "01" ~ TRUE,
                             TRUE ~ FALSE))

# obs_stat <- admissions_test_data %>% 
#   mutate(month = as.numeric(month)) %>% 
#   filter(month < 4) %>% 
#   summarise(winter_admissions = mean(number_admissions)) %>% 
#   pull()

null_distribution <- admissions_test_data %>%
  specify(number_admissions ~ january) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute") %>%
  calculate(stat = "diff in means", order = c(TRUE, FALSE))

observed_stat <- admissions_test_data %>% 
  specify(number_admissions ~ january) %>%
  calculate(stat = "diff in means", order = c(TRUE, FALSE))


null_distribution %>%
  visualise() +
  shade_p_value(obs_stat = observed_stat, direction = "right")
```

